# copies the tag from a earlier commit to current commit
# helps with dev release automation (as it should be {current version}-dev)
name: append tag to commit

on:
  push:
    branches:
      - dev
    tags-ignore: 
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          $tag = git tag|?{$_ -like "v*"}|sort|select -first 1
          if (!$tag){
            $tag = "v0.0.0"
          }
          echo "tag=$tag" >> $env:GITHUB_OUTPUT
        id: tag
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.tag.outputs.tag }}" 