on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

# env:
#   Variables: .github/variables/common.env

name: Build and Release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          distribution: goreleasergo
          args: release --clean --verbose --draft



