on:
  push:
    tags:
      - "v*.*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  Variables: .github/variables/common.env

name: Build and Release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6

      - name: Publish Binaries
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.ref }}
          tag: ${{ github.ref }}
          file: dist/*
          file_glob: true
          overwrite: true
          draft: true
